INSERT INTO users (name, email, password, avatar_url)
VALUES
('Julius Witting', 'user1@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/1.png'),
('Otis Lang V', 'user2@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/2.png'),
('Nichole Shanahan PhD', 'user3@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/3.png'),
('Bennie Moen', 'user4@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/4.png'),
('Catherine Carter', 'user5@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/5.png'),
('Daniel Paucek', 'user6@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/6.png'),
('Cora Auer DDS', 'user7@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/7.png'),
('Hannah Predovic', 'user8@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/8.png'),
('Dean Kilback', 'user9@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/9.png'),
('Shirley Schuster I', 'user10@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/10.png'),
('Willie King', 'user11@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/11.png'),
('Dr. Brendan Veum', 'user12@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/12.png'),
('Mercedes Simonis', 'user13@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/13.png'),
('Glen Cruickshank', 'user14@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/14.png'),
('Timmy Rippin', 'user15@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/15.png'),
('Ms. Violet Mann', 'user16@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/16.png'),
('Heidi Sporer', 'user17@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/17.png'),
('Shaun Wolf', 'user18@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/18.png'),
('Lionel Goyette', 'user19@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/19.png'),
('Kelly Smitham', 'user20@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/20.png'),
('Gwendolyn Lubowitz', 'user21@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/21.png'),
('Bradley Mraz', 'user22@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/22.png'),
('Stephanie Botsford', 'user23@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/23.png'),
('Mr. Alex Frami', 'user24@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/24.png'),
('Kenneth Batz', 'user25@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/25.png'),
('Eleanor Jones', 'user26@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/26.png'),
('Emilio Daniel DVM', 'user27@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/27.png'),
('Kristen Cummings', 'user28@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/28.png'),
('Christy Goodwin', 'user29@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/29.png'),
('Sarah Dicki', 'user30@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/30.png'),
('Crystal Hoppe', 'user31@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/31.png'),
('Willis Goldner', 'user32@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/32.png'),
('Paul Grady', 'user33@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/33.png'),
('Ignacio Bogan', 'user34@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/34.png'),
('Frankie Bailey', 'user35@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/35.png'),
('Shannon Roberts', 'user36@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/36.png'),
('Johnnie Berge', 'user37@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/37.png'),
('Sophia Jaskolski', 'user38@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/38.png'),
('Bobbie Halvorson', 'user39@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/39.png'),
('Steven Stehr', 'user40@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/40.png'),
('Kimberly Robel', 'user41@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/41.png'),
('Mark Zboncak', 'user42@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/42.png'),
('Natalie Beer', 'user43@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/43.png'),
('Shaun Hegmann', 'user44@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/44.png'),
('Rolando Wyman', 'user45@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/45.png'),
('Leona Nikolaus', 'user46@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/46.png'),
('Lynda Cartwright', 'user47@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/47.png'),
('Dr. Dominic Bauch', 'user48@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/48.png'),
('Theresa Mueller', 'user49@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/49.png'),
('Beulah O''Reilly', 'user50@test.com', '$2b$12$CRwCuPk4TPwF2SUsGvb9l.9xJGo3xcVsuvJuF6ehktpJIGsGIFtmS', '/images/users/50.png');
